// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/documents": {
    params: {};
  };
  "/dashboard/documents/view/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/dashboard/documents" | "/dashboard/documents/view/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "layout/index.tsx": {
    id: "layout/index";
    page: "/dashboard" | "/dashboard/documents" | "/dashboard/documents/view/:id";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/documents" | "/dashboard/documents/view/:id";
  };
  "routes/document-home.tsx": {
    id: "routes/document-home";
    page: "/dashboard/documents";
  };
  "routes/document-view.tsx": {
    id: "routes/document-view";
    page: "/dashboard/documents/view/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "layout/index": typeof import("./app/layout/index.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/document-home": typeof import("./app/routes/document-home.tsx");
  "routes/document-view": typeof import("./app/routes/document-view.tsx");
};